export const carsNames: Array<string> = [
    'Audi',
    'BMW',
    'Mercedes',
    'Volkswagen',
    'Ford',
    'Toyota',
    'Honda',
    'Nissan',
    'Chevrolet',
    'Hyundai',
    'Kia',
    'Mazda',
    'Subaru',
    'Volvo',
    'Jaguar',
    'Land Rover',
    'Tesla',
    'Porsche',
    'Ferrari',
    'Lamborghini'
];

export const carsModels: Array<string> = [
    'A3',
    'X5',
    'C-Class',
    'Golf',
    'Focus',
    'Corolla',
    'Civic',
    'Sentra',
    'Cruze',
    'Elantra',
    'Sportage',
    'CX-5',
    'Impreza',
    'S60',
    'F-Type',
    'Range Rover',
    'Model S',
    '911',
    '488 GTB',
    'Huracan'
  ];
